accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns=[
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

riskcalc/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='homepage'),#homepage url
    path('accounts/', include('accounts.urls')),#urls for account- login and signup
    path('userdata/', include('userdata.urls')),#urls for user data/ input page
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userdata/urls.py
from django.urls import path

from . import views

app_name = 'userdata'
urlpatterns = [
    path('patienttype/', views.patienttype, name='patienttype'),
    path('userinput/', views.user_input, name='userinput'),
]

accounts/models.py
from django.db import models

userdata/models.py
from django.db import models

class Userdata(models.Model):
    hospitalid= models.SlugField(primary_key=True, unique=True)   #hospital_id for patient  #must be unique
    name      = models.CharField(max_length=40, default='')      #name
    age       = models.IntegerField()   #agefield
    hpd       = models.BooleanField()   #history of pulmonary disease
    ckd       = models.BooleanField()   #history of ckd
    dm        = models.BooleanField()   #history of DM
    htn       = models.BooleanField()   #history of HTN
    hiv       = models.BooleanField()   #history of HIV
    trans     = models.BooleanField()   #immunosuppression/transplant
    resrate   = models.IntegerField()   #respiratory rate to be taken from electronics
    heartrate = models.IntegerField()   #heart rate to be taken from electronics
    spo       = models.IntegerField()   #spo2 to be taken from electronics
    ddimer    = models.IntegerField(null=True)   #ddimer ug/ml
    cpk       = models.IntegerField(null=True)   #cpk     U/L
    crp       = models.IntegerField(null=True)   #crp     mg/L
    ldh       = models.IntegerField(null=True)   #LDH     U/L
    tropo     = models.FloatField(null=True)     #tropopin ng/mL
    ferr      = models.IntegerField(null=True)   #ferritin ug/L
    absolute  = models.FloatField(null=True)     #Absolute Lymphocyte count
    ctscan    = models.IntegerField(null=True)   #CT SCAN
    abg       = models.IntegerField(null=True)   #ABG (P/F ratio)

    def __str__(self):
        return self.name

userdata/forms.py
from django.forms import ModelForm
from .models import Userdata

class Userform(ModelForm):
    class Meta:
        model = Userdata
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponse

#user login view for sign up or login
def login_view(request):
    if request.method == 'POST':
        if request.POST.get('login') == 'login':
            form=AuthenticationForm(data=request.POST)
            if form.is_valid():
                user = form.get_user()
                login(request, user)
                return  redirect('userdata:patienttype')
            else:
                authform = AuthenticationForm()
        if request.POST.get('signup')== 'signup':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                login(request, user)
                return  redirect('userdata:patienttype')
            else: userform = UserCreationForm()
    else:
        authform = AuthenticationForm()
        userform = UserCreationForm()
        return  render(request, 'accounts/login.html', {'authform': authform, 'userform' : userform})

#logging out users
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('')

riskcalc/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

userdata/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from . import forms
from django.contrib.auth.decorators import login_required
from .models import Userdata

@login_required(login_url="/accounts/login/") #login check
def patienttype(request):
    return render(request, 'userdata/patienttype.html')

 #input form
def user_input(request):
    if request.method == 'POST':
        if 'patient' in request.POST.keys():
            if request.POST.get('patient') == 'existing':   #checking if existing patient requested
                id = request.POST.get('hospitalid')
                try:
                    queryform = Userdata.objects.get(hospitalid = id)
                    userform = forms.Userform(instance=queryform)
                    return render(request, 'userdata/calculate.html', {'userform':userform})
                except Exception as errmsg:
                    return render(request, 'userdata/patienttype.html', {'errmsg': errmsg})
            if request.POST.get('patient') == 'new':        #checks for new patient
                id = request.POST.get('hospitalid')
                try:
                    queryform = Userdata.objects.get(hospitalid = id)
                    errmsg = "ID already exists"
                    return render(request, 'userdata/patienttype.html', {'errmsg':errmsg})
                except:
                    userform = forms.Userform(initial={'hospitalid': id})
                    return render(request, 'userdata/calculate.html', {'userform': userform})

        model, created = Userdata.objects.get_or_create(hospitalid = request.POST.get('hospitalid'))
        form = forms.Userform(request.POST, instance = model)
        if form.is_valid():
            form.save()
            count, message = checkparams(request.POST)
            return render(request, 'userdata/result.html', {'count':count, 'message': message})
        else:
            errmsg = form.errors.as_data()
            return render(request, 'userdata/calculate.html', {'errmsg':errmsg})
    else:
        userform = forms.Userform()
    return render(request, 'userdata/calculate.html',  {'userform': userform})



def checkparams(params):
    total = 0
    total_param = 21
    count_epi = 0
    count_vital = 0
    count_lab = 0
    riskMessage = "Risk returned null"
    if int(params['age']) > 55:
        counter += 1
    if 'hpd' in params:
        count_epi += 1
    if 'ckd' in params:
        count_epi += 1
    if 'dm' in params:
        count_epi += 1
    if 'htn' in params:
        count_epi += 1
    if 'hiv' in params:
        count_epi += 1
    if 'trans' in params:
        count_epi +=  1
    if int(params['resrate']) > 24:
        count_vital += 1
    if int(params['heartrate']) > 125:
        count_vital += 1
    if int(params['spo']) < 90:
        count_vital += 1
    if int(params['ddimer']) != None and int(params['ddimer']) > 1000:
        count_lab += 1
    if int(params['cpk']) != None and int(params['cpk']) > 400:
        count_lab += 1
    if int(params['crp']) != None and int(params['crp']) > 100:
        count_lab += 1
    if int(params['ldh']) != None and int(params['ldh']) > 245:
        count_lab += 1
    if float(params['tropo']) != None and float(params['tropo']) > 0.1:
        count_lab += 1
    if int(params['ferr']) != None and int(params['ferr']) > 500:
        count_lab += 1
    if float(params['absolute']) != None and float(params['absolute']) < 0.8:
        count_lab += 1
    total = count_epi+count_lab+count_vital
    risk = (total/total_param) * 10
    risk = round(risk, 2)
    total_vl = count_lab+count_vital
    if(count_epi>0 and count_vital>0 and count_lab>0):
        riskMessage = "High Risk"
        return risk,riskMessage
    elif(tot_vl == 2 and count_lab != 0 and count_vital != 0):
        riskMessage = "Moderate Risk"
        return risk,riskMessage
    elif(tot_vl >= 2):
        riskMessage = "High Risk"
        return risk,riskMessage
    elif(count_epidem > 0 and (count_lab == 1 or count_vital == 1)):
        riskMessage = "Moderate Risk"
        return risk,riskMessage
    elif(total < 2 or (count_epidem > 0 and count_lab == 0 and count_vital == 0)):
        riskMessage = "Low Risk"
        return risk, riskMessage
    return risk,riskMessage

accounts/templates/accounts/login.html
{% load static from static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial=scale=1.0"/>
	<meta http-equiv="X-UA-Compatible" content="ie=edge"/>
	<link
	  rel="stylesheet"
	  href="https://use.fontawesome.com/release/v5.8.1/css/all.css"
	  integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
	  crossorigin="anonymous"
	  />
	<title>LOGIN admin/user</title>
	<link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">
</head>


</body>
<h2>RiskCal login/signup </h2>
<div class="container" id="container">
	<div class="form-container sign-up-container">
		<form action="{% url 'accounts:login' %}" method="post">
			{% csrf_token %}
			<h1>Create Account/New Patient</h1>

			<span>or use your email for registration</span>
			{% for field in userform %}
			{{field.label}}
			{{field}}
			{% endfor %}
			<input type="submit" name="signup" value="signup" formmethod="post">
		</form>
	</div>
	<div class="form-container sign-in-container">
		<form action="{% url 'accounts:login' %}" method="post">
			{% csrf_token %}
			<h1>Sign in/Existing Patient</h1>

			<span>or use your account</span>
			{% for field in authform %}
			{{field.label}}
			{{field}}
			{% endfor %}
			<input type="submit" name="login" value="login" formmethod='post'>
		</form>
	</div>
	<div class="overlay-container">
		<div class="overlay">
			<div class="overlay-panel overlay-left">
				<h1>Welcome Back!</h1>
				<p>To keep connected with us please login with your personal info</p>
				<button class="ghost" id="signIn">Sign In</button>
			</div>
			<div class="overlay-panel overlay-right">
				<h1>Welcome</h1>
				<p>Enter your details here</p>
				<button class="ghost" id="signUp">Sign Up</button>
			</div>
		</div>
	</div>
</div>

<script src="{% static 'index.js' %}"></script>
</body>
</html>

templates/homepage.html
{% load static from static %}
<!doctype html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>RiskCalculator</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'about.css' %}">
</head>

<body>
  <header>
    <div class="container-fluid p-0">
      <div class="nav-btn navbar navbar-expand-lg navbar-light bg-white">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="nav-links">
            <ul class="navbar-nav mr-auto">
              <li class="nav-link" style="--i: .6s">
                <a href="#">Home</a>
              </li>
              <li class="nav-link" style="--i: .6s">
                <a href="{% url 'accounts:login' %}">Login/signup</a>
              </li>

            </ul>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="contactUsHeading">
    <h1 class="Heading">RISK CALCULATOR</h1>
  </div>
  <section>
    <div class="container-fluid p-0" id="who">
      <div class="row">
        <h2>Who Are WE</h2>
        <p>We examine people using sophesticated ai ml tools and tell them if they are at a risk.
        </p>
      </div>
    </div>
  </section>



  </section>
  <div class="connect p-0">
    <div class="flex-center">
     <a href=""><i class="fa fa-github fa-4x icon-3d"></i></a>
     <a href=""><i class="fa fa-facebook fa-4x icon-3d"></i></a>
     <a href=""><i class="fa fa-instagram fa-4x icon-3d"></i></a>
     <a href=""><i class="fa fa-twitter fa-4x icon-3d"></i></a>
    </div>
  </div>

   <footer>
    <p>© Copyright 2020 MIT-Manipal</p>

  </footer>


</body>

</html>

userdata/templates/userdata/calculate.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>trial</title>
  </head>
  <body>
    {% if errmsg %}
    <p>{{errmsg}}</p>
    {% endif %}
    <form action="{% url 'userdata:userinput' %}" method="post">
      {% csrf_token %}
      {{userform.hospitalid.label}}
      {{userform.hospitalid}}
      {{userform.name.label}}
      {{userform.name}}
      {{userform.age.label}}
      {{userform.age}}
      {{userform.hpd.label}}
      {{userform.hpd}}
      {{userform.ckd.label}}
      {{userform.ckd}}
      {{userform.dm.label}}
      {{userform.dm}}
      {{userform.htn.label}}
      {{userform.htn}}
      {{userform.hiv.label}}
      {{userform.hiv}}
      {{userform.trans.label}}
      {{userform.trans}}
      {{userform.resrate.label}}
      {{userform.resrate}}
      {{userform.heartrate.label}}
      {{userform.heartrate}}
      {{userform.spo.label}}
      {{userform.spo}}
      {{userform.ddimer.label}}
      {{userform.ddimer}}
      {{userform.cpk.label}}
      {{userform.cpk}}
      {{userform.crp.label}}
      {{userform.crp}}
      {{userform.ldh.label}}
      {{userform.ldh}}
      {{userform.tropo.label}}
      {{userform.tropo}}
      {{userform.ferr.label}}
      {{userform.ferr}}
      {{userform.absolute.label}}
      {{userform.absolute}}
      {{userform.ctscan.label}}
      {{userform.ctscan}}
      {{userform.abg.label}}
      {{userform.abg}}
      <input type="submit" value="Submit" formmethod="POST">
    </form>
  </body>
</html>

userdata/templates/userdata/patienttype.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Patient</title>
  </head>
  <body>
    {% if errmsg %}
    {{errmsg}}
    {% endif %}
    <form action="{% url 'userdata:userinput' %}" method="post">
      {% csrf_token %}
      <p>New Patient <input type="radio" name="patient" value="new"></p>
      <p>Existing patient <input type="radio" name="patient" value="existing"></p>
      <p>Id: <input type="text" name="hospitalid"></p>
      <input type="submit" formmethod="post">
    </form>
  </body>
</html>

userdata/templates/userdata/result.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Result</title>
  </head>
  <body>
    <p>Your Risk Factor is {{count}}</p>
    <p>Risk Message: {{message}}</p>
    <a href="{% url 'userdata:patienttype' %}">Back to patienttype</a>
  </body>
</html>